In [1]:
2+5

7

In [2]:
2+2

4

In [3]:
print("Hello World")

Hello World


In [10]:
23+9

32

### Simple Expressions in Python

#### Arithemetic Operators

In [3]:
8+7

15

In [5]:
10-2

8

In [7]:
12*9

108

In [11]:
15/4

3.75

In [13]:
15//4

3

In [15]:
122/10

12.2

In [23]:
-122//10

-13

In [34]:
130%11 ##Remainder

9

In [40]:
2**3 # Power (Exponential)

8

In [47]:
x = -176//10

In [49]:
x

-18

#### String Operators

In [61]:
print("Hello World")

Hello World


In [63]:
Greeting = "Hello world"

In [67]:
print(Greeting)

Hello world


In [73]:
"Good Evening" + " to all of You" # Concatenation

'Good Evening to all of You'

In [79]:
"Good" + " " + "Evening" + " " + "to all of You!!"

'Good Evening to all of You!!'

In [97]:
print(" Good Evening\n" * 3)

 Good Evening
 Good Evening
 Good Evening



#### Comparision

In [104]:
5 == 5 # Is 5 equal to 5

True

In [108]:
4 != 5

True

In [110]:
5 > 3

True

In [112]:
5 < 3

False

In [114]:
5 >= 5 # is 5 greater than or equal to 5.

True

#### Variables

In [119]:
age = 40
age

40

In [121]:
age + 3 * 4

52

In [155]:
Name = "Priya"

In [161]:
Greet = "Hi {}".format(Name)

In [163]:
print(Greet)

Hi Priya


In [169]:
a = 5
b = 3
c = a - b
print(c)

2


In [175]:
Name = input()

 Saurabh


In [177]:
Age = input()

 25


In [185]:
Info = print('Your Name is {} and you are {} years old'.format(Name,Age))

Your Name is Saurabh and you are 25 years old


In [187]:
Name = input()
Age = input()
Info = print('Your Name is {} and you are {} years old'.format(Name,Age))

 Saurabh
 29


Your Name is Saurabh and you are 29 years old


## Data Structures

In [194]:
## List, Tuple, Dictionaries, Set

##### List

In [198]:
list = [1,2,3,4,5]

In [200]:
list

[1, 2, 3, 4, 5]

In [91]:
Fruits = ['apple','banana','orange','grapes']

In [93]:
Comb = ['apple',24,'banana',22,13,'grapes']

In [210]:
Comb

['apple', 24, 'banana', 22, 13, 'grapes']

In [217]:
print(Comb[2])

banana


In [233]:
Comb[0:2]

['apple', 24]

In [240]:
ListofList = [[1,2],['apple','banana'],['x','y','z']] # Nested List

In [254]:
print(ListofList[1][1])

banana


#### List Operators (Build in)

In [256]:
Comb.append('mango') ## Adds an elenment at the end

In [258]:
Comb

['apple', 24, 'banana', 22, 13, 'grapes', 'mango']

In [324]:
Comb.insert(2,'blueberry') ## Adds an element at specified index

In [262]:
Comb

['apple', 24, 'blueberry', 'banana', 22, 13, 'grapes', 'mango']

In [264]:
Comb.remove(13) ## Removed the element 

In [266]:
Comb

['apple', 24, 'blueberry', 'banana', 22, 'grapes', 'mango']

In [274]:
Comb.pop() ## Removes the last element and displays the same as output

'grapes'

In [278]:
Comb.append(['grapes','mango'])

In [282]:
Comb.pop()

['grapes', 'mango']

In [286]:
Comb.append('grapes')
Comb.append('mango')

In [288]:
Comb

['apple', 24, 'blueberry', 'banana', 22, 'grapes', 'mango']

In [290]:
Comb.append(13)

In [294]:
Comb.append(13)

In [296]:
Comb

['apple', 24, 'blueberry', 'banana', 22, 'grapes', 'mango', 13, 13]

In [304]:
Comb.remove(13)

In [306]:
Comb

['apple', 24, 'blueberry', 'banana', 22, 'grapes', 'mango']

In [308]:
Comb.append(13)
Comb.insert(3,13)

In [310]:
Comb

['apple', 24, 'blueberry', 13, 'banana', 22, 'grapes', 'mango', 13]

In [312]:
Comb.remove(13)

In [314]:
Comb

['apple', 24, 'blueberry', 'banana', 22, 'grapes', 'mango', 13]

In [316]:
Comb.clear() ## Deletes all elements in the list

In [318]:
Comb

[]

In [320]:
Comb = ['apple',24,'banana',22,13,'grapes']

In [326]:
Comb

['apple', 24, 'blueberry', 'banana', 22, 13, 'grapes']

In [328]:
len(Comb) # Number of elements in the list

7

In [350]:
Comb[-2]

13

##### List Concatenation

In [368]:
print(Comb)
print(list)

['apple', 24, 'blueberry', 'banana', 22, 13, 'grapes']
[1, 2, 3, 4, 5]


In [370]:
Merge = Comb + list

In [374]:
Merge_2 = list + Comb

In [378]:
print(Merge)
Merge_2

['apple', 24, 'blueberry', 'banana', 22, 13, 'grapes', 1, 2, 3, 4, 5]


[1, 2, 3, 4, 5, 'apple', 24, 'blueberry', 'banana', 22, 13, 'grapes']

In [404]:
Merge.count(13)  ## Count of a specific element

1

### Tuples

In [332]:
tuple = (1,5,9)

In [334]:
tuple

(1, 5, 9)

In [336]:
# Indexing, Build in Methods - Change the elements

In [338]:
Fruits = ('apple','banana','orange','grapes')

In [340]:
Fruits

('apple', 'banana', 'orange', 'grapes')

In [342]:
Fruits[0]

'apple'

In [344]:
Fruits[0:2]

('apple', 'banana')

In [356]:
print(Fruits[-1])

grapes


In [380]:
Mer_tuple = Fruits + tuple # Concatenation of Tuple

In [390]:
print(Mer_tuple[2])

orange


In [392]:
print(Mer_tuple)

('apple', 'banana', 'orange', 'grapes', 1, 5, 9)


In [398]:
repeated_tuple = Mer_tuple * 3
repeated_tuple

('apple',
 'banana',
 'orange',
 'grapes',
 1,
 5,
 9,
 'apple',
 'banana',
 'orange',
 'grapes',
 1,
 5,
 9,
 'apple',
 'banana',
 'orange',
 'grapes',
 1,
 5,
 9)

In [406]:
len(repeated_tuple) # Number of elements in the tuple

21

In [412]:
repeated_tuple.count('grape')  ## Count of a specific element

0

In [422]:
sum(tuple)

15

In [424]:
Nested_tuple = (1,2,(4,5),(6,7))

In [426]:
Nested_tuple

(1, 2, (4, 5), (6, 7))

In [432]:
Nested_tuple[2][1]

5

In [438]:
sum(Nested_tuple[3])

13

## Dictionaries

In [5]:
Saurabh_info = {'Name':'Saurabh','age':30,'city':'Bangalore','Experience' : 12}

In [7]:
Saurabh_info

{'Name': 'Saurabh', 'age': 30, 'city': 'Bangalore', 'Experience': 12}

In [9]:
Saurabh_info.keys()

dict_keys(['Name', 'age', 'city', 'Experience'])

In [11]:
Saurabh_info.values()

dict_values(['Saurabh', 30, 'Bangalore', 12])

In [13]:
Saurabh_info['city']

'Bangalore'

In [15]:
Saurabh_info['Experience']

12

#### Dictionary Methods

In [20]:
Saurabh_info.pop('Experience') # Removes the specified element in the command

12

In [22]:
Saurabh_info

{'Name': 'Saurabh', 'age': 30, 'city': 'Bangalore'}

In [24]:
Saurabh_info['Experience'] = 12

In [26]:
Saurabh_info

{'Name': 'Saurabh', 'age': 30, 'city': 'Bangalore', 'Experience': 12}

In [32]:
Saurabh_info.items() # Displays all Key Value Pair

dict_items([('Name', 'Saurabh'), ('age', 30), ('city', 'Bangalore'), ('Experience', 12)])

In [87]:
Saurabh_info.update({'Experience':14})

In [36]:
Saurabh_info

{'Name': 'Saurabh', 'age': 30, 'city': 'Bangalore', 'Experience': 14}

In [40]:
Copy = Saurabh_info.copy()

In [42]:
Copy

{'Name': 'Saurabh', 'age': 30, 'city': 'Bangalore', 'Experience': 14}

In [44]:
Saurabh_info['Experience'] = 13

In [46]:
Saurabh_info

{'Name': 'Saurabh', 'age': 30, 'city': 'Bangalore', 'Experience': 13}

In [59]:
Saurabh_info.clear()

In [50]:
Saurabh_info

{}

In [77]:
Saurabh_info = {'Name':'Saurabh','age':30,'city':'Bangalore','Experience' : 12}

In [89]:
Saurabh_info

{'Name': 'Saurabh', 'age': 30, 'city': 'Bangalore', 'Experience': 14}

#### Nested Dictionaries

In [6]:
Employee_info = {'EM2403': 
                 {'name': 'Alice',
                    'age': 30,
                    'city': 'New York'},
                'EM2409': {
                    'name': 'Bob',
                    'age': 25,
                    'city': 'San Francisco'
                },
                'EM2390': {
                    'name': 'Charlie',
                    'age': 35,
                    'city': 'Seattle'
                },
                'EM2399': {
                    'name': 'Subhash',
                    'age': 35,
                    'city': 'Washington'
                }
            }

In [93]:
Employee_info

{'EM2403': {'name': 'Alice', 'age': 30, 'city': 'New York'},
 'EM2409': {'name': 'Bob', 'age': 25, 'city': 'San Francisco'},
 'EM2390': {'name': 'Charlie', 'age': 35, 'city': 'Seattle'},
 'EM2399': {'name': 'Subhash', 'age': 35, 'city': 'Washington'}}

In [101]:
print(Employee_info['EM2390']['name'])

Charlie


In [105]:
Employee_info['EM2399'].update({'city': 'Mumbai'})

In [107]:
Employee_info

{'EM2403': {'name': 'Alice', 'age': 30, 'city': 'New York'},
 'EM2409': {'name': 'Bob', 'age': 25, 'city': 'San Francisco'},
 'EM2390': {'name': 'Charlie', 'age': 35, 'city': 'Seattle'},
 'EM2399': {'name': 'Subhash', 'age': 35, 'city': 'Mumbai'}}

## Sets

#### Creating Sets

In [3]:
Set_1 = {1,3,5,7,9}

In [5]:
Set_1.add(11) # Adds the element towards the end

In [7]:
Set_1

{1, 3, 5, 7, 9, 11}

In [9]:
Set_2 = {2,1,3,1,4,2,4,5,1,2,3,4,5}

In [11]:
Set_2

{1, 2, 3, 4, 5}

In [13]:
Set_1.add('Hello')

In [15]:
Set_1

{1, 11, 3, 5, 7, 9, 'Hello'}

In [17]:
Mul_of_3 = {3,6,9,12,15}
Mul_of_4 = {4,8,12,16,20}

#### Union

In [20]:
Mul_of_3

{3, 6, 9, 12, 15}

In [22]:
Mul_of_4

{4, 8, 12, 16, 20}

In [24]:
Combined = Mul_of_3.union(Mul_of_4)

In [26]:
Combined

{3, 4, 6, 8, 9, 12, 15, 16, 20}

In [28]:
Mul_of_4.union(Mul_of_3)

{3, 4, 6, 8, 9, 12, 15, 16, 20}

#### Intersection

In [31]:
Common = Mul_of_3.intersection(Mul_of_4)

In [33]:
Common

{12}

In [35]:
Mul_of_4

{4, 8, 12, 16, 20}

In [39]:
Mul_of_4.intersection_update(Mul_of_4)

In [41]:
Mul_of_4

{4, 8, 12, 16, 20}

##### Difference

In [43]:
print(Mul_of_3)
print(Mul_of_4)

{3, 6, 9, 12, 15}
{16, 4, 20, 8, 12}


In [45]:
diff = Mul_of_3 - Mul_of_4

In [47]:
diff

{3, 6, 9, 15}

In [49]:
Mul_of_4-Mul_of_3

{4, 8, 16, 20}

In [51]:
print(Mul_of_3)
print(Mul_of_4)

{3, 6, 9, 12, 15}
{16, 4, 20, 8, 12}


In [53]:
Diffset = Mul_of_3.difference(Mul_of_4)

In [55]:
Diffset

{3, 6, 9, 15}

In [57]:
Mul_of_3

{3, 6, 9, 12, 15}

In [59]:
Mul_of_3.difference_update(Mul_of_4)

In [61]:
Mul_of_3

{3, 6, 9, 15}

#### Symmetric Difference

In [64]:
Mul_of_3.symmetric_difference(Mul_of_4)

{3, 4, 6, 8, 9, 12, 15, 16, 20}

In [66]:
Mul_of_3.symmetric_difference_update(Mul_of_4)

In [68]:
Mul_of_3

{3, 4, 6, 8, 9, 12, 15, 16, 20}

In [70]:
Mul_of_3.remove(8)

In [72]:
Mul_of_3

{3, 4, 6, 9, 12, 15, 16, 20}

In [74]:
Mul_of_4

{4, 8, 12, 16, 20}

In [76]:
Mul_of_4.remove(8)

#### Conditional Statements

In [79]:
x = int(input('Enter the Number'))
if x > 2:
    print('The given number is Greater than 2')   

Enter the Number 33


The given number is Greater than 2


In [81]:
x = int(input('Enter the Number'))
if x % 2 == 0:
    print('The given number is Even')
else:
    print('The given number is Odd')

Enter the Number 33


The given number is Odd


In [83]:
x = int(input('Enter the Number'))
if x % 3 == 0:
    print('The given number is a Multiple of 3')
elif x % 4 == 0:
    print('The given number is a Multiple of 4')
elif x % 5 == 0:
    print('The given number is a Multiple of 5')
else:
    print('The given number is not a Multiple of any one of 3,4 or 5')

Enter the Number 234


The given number is a Multiple of 3


### Loops

In [275]:
## for, while

In [85]:
for i in Mul_of_3:
    print(i+3)

6
7
9
12
15
18
19
23


In [95]:
for i in Fruits:
    print(i)

apple
banana
orange
grapes


In [97]:
for i in range(1,10):
    print('The Square of {} is {}'.format(i,i**2))

The Square of 1 is 1
The Square of 2 is 4
The Square of 3 is 9
The Square of 4 is 16
The Square of 5 is 25
The Square of 6 is 36
The Square of 7 is 49
The Square of 8 is 64
The Square of 9 is 81


##### While loop

In [99]:
i = 0
while i <= 10:
    print(i)
    i = i + 1

0
1
2
3
4
5
6
7
8
9
10


###### List Comprehension

In [101]:
M3 = [1,2,3,4,5,6,7,8,9]

In [103]:
M3Squres = [x**2 for x in M3]

In [105]:
M3Squres

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [107]:
Even = [x for x in M3 if x%2 == 0]

In [109]:
Even

[2, 4, 6, 8]

In [111]:
Odd = [x for x in M3 if x%2 != 0]

In [113]:
Odd

[1, 3, 5, 7, 9]

In [115]:
First20 = [x for x in range(1,21)]

In [117]:
First20

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [119]:
Cubes = {'The cube of {} is'.format(x):x**3 for x in Mul_of_3}

In [121]:
Cubes

{'The cube of 3 is': 27,
 'The cube of 4 is': 64,
 'The cube of 6 is': 216,
 'The cube of 9 is': 729,
 'The cube of 12 is': 1728,
 'The cube of 15 is': 3375,
 'The cube of 16 is': 4096,
 'The cube of 20 is': 8000}

In [123]:
SquareCubes = {'Number is {}'.format(x):{'Its Square is {}'.format(x**2),'Its Cube is {}'.format(x**3)} for x in Mul_of_4}

In [125]:
SquareCubes

{'Number is 16': {'Its Cube is 4096', 'Its Square is 256'},
 'Number is 4': {'Its Cube is 64', 'Its Square is 16'},
 'Number is 20': {'Its Cube is 8000', 'Its Square is 400'},
 'Number is 12': {'Its Cube is 1728', 'Its Square is 144'}}

### Loops in python

#### Nested Loop

In [231]:
Num = int(input("Enter your number"))

for i in range(2,Num):
    if Num == 1:
        print("The number is Neither Prime nor Composite")
    elif Num == 2:
        print("The Number is Prime")
    elif Num % i == 0:
        print("The number is Composite")
        break
    else: 
        print("The Number is Prime")
        break

Enter your number 9


The Number is Prime


In [281]:
x = int(input("Enter your number"))

for i in range(4,x):
    if Num % i == 0:
        print("The number is Composite")
        break
    else: 
        print("The Number is Prime")
        break

Enter your number 6


The Number is Prime


In [251]:
x = int(input('Enter a number'))
i = 1
a = 0

while i <= x:
    j = 1
    while j <= x:
        if i % j == 0:
            a += 1
        j += 1
   
    if a == 2:  
        print(i, 'is a prime number')
   
    i += 1
    a = 0  

Enter a number 13


2 is a prime number
3 is a prime number
5 is a prime number
7 is a prime number
11 is a prime number
13 is a prime number


In [396]:
x = int(input("Enter the number:"))

for i in range(1,x):
    if x == 1:
        print("Number is neither prime nor composite")
        break
    elif x == 2:
        print("Number is prime")
        break
    elif x == 3:
        print("Number is prime")
        break
    if x % i ==0:
        print("The number is composite")
        break
    else:
        print("The number is prime")
        break


Enter the number: 5


The number is composite


In [305]:
for i in range(1,11):
    print("The table of {}".format(i))
    for j in range (1,11):
        print("{} x {} = {}".format(i,j,i*j))
    print()

The table of 1
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10

The table of 2
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

The table of 3
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

The table of 4
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

The table of 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

The table of 6
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

The table of 7
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

The table of 8
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80

The ta

##### Break

In [357]:
list = [x for x in range(1,100) if x % 3 == 0]

In [329]:
for i in range(1,100):
    if i == 23:
        break  # Breaks the code once the objective is achieved
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


##### Continue

In [346]:
for i in list:
    if i % 5 == 0 or i % 7 == 0:
        continue      # It Skips the i's which follow the condition mentioned
    print(i)

3
6
9
12
18
24
27
33
36
39
48
51
54
57
66
69
72
78
81
87
93
96
99


##### Pass

In [359]:
for i in range(1,100):
    for j in range(1,50):
        pass               # Implement the logic later
print('The code is incomplete')

The code is incomplete


### Def Function

In [368]:
def sumproduct(a,b):
    return 2*a + 3*b

In [366]:
sumproduct(3,9)

33

In [374]:
def sumsquares(a,b):
    x = a**2
    y = b**2
    z = x + y
    return z

In [376]:
sumsquares(10,11)

221

In [380]:
def prime_number_check(x):
    for i in range(1,x):
        if x == 1:
            print("Number is neither prime nor composite")
            break
        elif x == 2:
            print("Number is prime")
            break
        elif x == 3:
            print("Number is prime")
            break
        if x % i ==0:
            print("The number is composite")
            break
        else:
            print("The number is prime")
            break

In [386]:
prime_number_check(101)

The number is composite


In [361]:
# Numpy
# Pandas
# Matplotlib
# Seaborn
# Scipy
# Sklearn

#### Numpy

In [399]:
## pip install numpy
import numpy as np

In [403]:
arr = np.array([x for x in range(1,6)])

In [407]:
print(arr)

[1 2 3 4 5]


##### Create Arrays

In [422]:
a = np.array([[x for x in range(1,4)],[7,8,9]])

In [424]:
print(a)

[[1 2 3]
 [7 8 9]]


In [430]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [434]:
ones = np.ones((3,3))

In [436]:
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [440]:
consecutive = np.arange(11)

In [464]:
print(consecutive)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [446]:
a.shape

(2, 3)

In [448]:
b.shape

(2, 3)

In [450]:
ones.shape

(3, 3)

In [452]:
ones.ndim

2

In [454]:
ones.size

9

In [456]:
ones.dtype

dtype('float64')

In [470]:
d = np.array([[1,2],[3,4],[5,6],[7,8]])

In [472]:
d.shape

(4, 2)

In [474]:
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [478]:
e = np.array([1,2,3,4,5,6,7,8])

In [480]:
print(e)

[1 2 3 4 5 6 7 8]


In [493]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [497]:
print(x)
print()
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [499]:
print(x + y)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [503]:
print(y-x)

[[ 9 18 27]
 [36 45 54]
 [63 72 81]]


In [507]:
print(x * y)
print()
print(y / x)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [509]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [511]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [538]:
angles = np.array([[30,45],[60,90],[120,180]])

In [540]:
np.sin(angles)

array([[ 0.16589613,  0.85090352],
       [-0.30481062,  0.89399666],
       [ 0.58061118, -0.80115264]])

In [527]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.94591015, 2.07944154, 2.19722458]])

##### Indexing and slicing

In [551]:
a[1,2]

9

In [553]:
a[1,1]

8

In [557]:
bigger = np.array([[x for x in range(1,6)],
                  [x for x in range(6,11)],
                 [x for x in range(11,16)],
                 [x for x in range(16,21)],
                 [x for x in range(21,26)]])

In [559]:
print(bigger)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [563]:
bigger[0:3,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [569]:
bigger[2:5,1:3]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [573]:
bigger[:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [575]:
bigger[1:3,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Pandas

In [115]:
import pandas as pd

##### Creating a Dataframe

In [8]:
Employee_info = {'EM2403': 
                 {'name': 'Alice',
                    'age': 30,
                    'city': 'New York'},
                'EM2409': {
                    'name': 'Bob',
                    'age': 25,
                    'city': 'San Francisco'
                },
                'EM2390': {
                    'name': 'Charlie',
                    'age': 35,
                    'city': 'Seattle'
                },
                'EM2399': {
                    'name': 'Subhash',
                    'age': 35,
                    'city': 'Washington'
                }
            }

In [10]:
Employee_info

{'EM2403': {'name': 'Alice', 'age': 30, 'city': 'New York'},
 'EM2409': {'name': 'Bob', 'age': 25, 'city': 'San Francisco'},
 'EM2390': {'name': 'Charlie', 'age': 35, 'city': 'Seattle'},
 'EM2399': {'name': 'Subhash', 'age': 35, 'city': 'Washington'}}

In [98]:
Emp_df = pd.DataFrame(Employee_info).T

In [100]:
Emp_df

name age           city
EM2403    Alice  30       New York
EM2409      Bob  25  San Francisco
EM2390  Charlie  35        Seattle
EM2399  Subhash  35     Washington

In [36]:
Emp_data = {'Emp_id': ['EM2403','EM2409','EM2390','EM2399'],
            'Name' : ['Alice','Bob','Charlie','Subhash'],
            'Age' : [30,25,35,35],
             'City' : ['New York','San Frasisco','Seattle','Washigton']}

In [38]:
Emp_df = pd.DataFrame(Emp_data)

In [44]:
Emp_df

Emp_id     Name  Age          City
0  EM2403    Alice   30      New York
1  EM2409      Bob   25  San Frasisco
2  EM2390  Charlie   35       Seattle
3  EM2399  Subhash   35     Washigton

In [90]:
Emp_df_Man = pd.DataFrame(data= [['EM2403','Alice','','New York'],
            ['EM2409','Bob',25,'San Fransico'],
            ['EM2390','Charlie',35,'Seattle'],
            ['EM2399','Subhash',35,'Washington']],columns = ['Emp_id','Name','Age','City'])

In [92]:
Emp_df_Man

Emp_id     Name Age          City
0  EM2403    Alice          New York
1  EM2409      Bob  25  San Fransico
2  EM2390  Charlie  35       Seattle
3  EM2399  Subhash  35    Washington

##### Import Data

In [252]:
covid_data = pd.read_csv('us-counties.csv')

In [169]:
covid_data

date      county       state     fips  cases  deaths
0        2020-01-21   Snohomish  Washington  53061.0      1     0.0
1        2020-01-22   Snohomish  Washington  53061.0      1     0.0
2        2020-01-23   Snohomish  Washington  53061.0      1     0.0
3        2020-01-24        Cook    Illinois  17031.0      1     0.0
4        2020-01-24   Snohomish  Washington  53061.0      1     0.0
...             ...         ...         ...      ...    ...     ...
2502827  2022-05-13  Sweetwater     Wyoming  56037.0  11088   126.0
2502828  2022-05-13       Teton     Wyoming  56039.0  10074    16.0
2502829  2022-05-13       Uinta     Wyoming  56041.0   5643    39.0
2502830  2022-05-13    Washakie     Wyoming  56043.0   2358    44.0
2502831  2022-05-13      Weston     Wyoming  56045.0   1588    18.0

[2502832 rows x 6 columns]

In [254]:
# Rename
covid_data.rename(columns={'date':'Date','county':'County','state':'State','fips':'FIPS','cases':'Cases','deaths':'Deaths'},inplace= True)

In [173]:
covid_data

Date      County       State     FIPS  Cases  Deaths
0        2020-01-21   Snohomish  Washington  53061.0      1     0.0
1        2020-01-22   Snohomish  Washington  53061.0      1     0.0
2        2020-01-23   Snohomish  Washington  53061.0      1     0.0
3        2020-01-24        Cook    Illinois  17031.0      1     0.0
4        2020-01-24   Snohomish  Washington  53061.0      1     0.0
...             ...         ...         ...      ...    ...     ...
2502827  2022-05-13  Sweetwater     Wyoming  56037.0  11088   126.0
2502828  2022-05-13       Teton     Wyoming  56039.0  10074    16.0
2502829  2022-05-13       Uinta     Wyoming  56041.0   5643    39.0
2502830  2022-05-13    Washakie     Wyoming  56043.0   2358    44.0
2502831  2022-05-13      Weston     Wyoming  56045.0   1588    18.0

[2502832 rows x 6 columns]

In [127]:
covid_data.head()  ## Gives top n rows; default = 5

Date     County       State     FIPS  Cases  Deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0
2  2020-01-23  Snohomish  Washington  53061.0      1     0.0
3  2020-01-24       Cook    Illinois  17031.0      1     0.0
4  2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [131]:
covid_data.head(2)

Date     County       State     FIPS  Cases  Deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0

In [133]:
covid_data.tail()  ## Gives bottom n rows; default = 5

Date      County    State     FIPS  Cases  Deaths
2502827  2022-05-13  Sweetwater  Wyoming  56037.0  11088   126.0
2502828  2022-05-13       Teton  Wyoming  56039.0  10074    16.0
2502829  2022-05-13       Uinta  Wyoming  56041.0   5643    39.0
2502830  2022-05-13    Washakie  Wyoming  56043.0   2358    44.0
2502831  2022-05-13      Weston  Wyoming  56045.0   1588    18.0

In [135]:
covid_data.tail(3)

Date    County    State     FIPS  Cases  Deaths
2502829  2022-05-13     Uinta  Wyoming  56041.0   5643    39.0
2502830  2022-05-13  Washakie  Wyoming  56043.0   2358    44.0
2502831  2022-05-13    Weston  Wyoming  56045.0   1588    18.0

In [256]:
covid_data = covid_data.drop('FIPS',axis=1) ## Drops a row/column

In [179]:
covid_data.head(3)

Date     County       State  Cases  Deaths
0  2020-01-21  Snohomish  Washington      1     0.0
1  2020-01-22  Snohomish  Washington      1     0.0
2  2020-01-23  Snohomish  Washington      1     0.0

In [186]:
## Info
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2502832 entries, 0 to 2502831
Data columns (total 5 columns):
 #   Column  Dtype  
---  ------  -----  
 0   Date    object 
 1   County  object 
 2   State   object 
 3   Cases   int64  
 4   Deaths  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 95.5+ MB


##### Slicing Rows and Columns

In [206]:
covid_data[['County','Cases','Deaths']].head()

County  Cases  Deaths
0  Snohomish      1     0.0
1  Snohomish      1     0.0
2  Snohomish      1     0.0
3       Cook      1     0.0
4  Snohomish      1     0.0

In [212]:
covid_data.County

0           Snohomish
1           Snohomish
2           Snohomish
3                Cook
4           Snohomish
              ...    
2502827    Sweetwater
2502828         Teton
2502829         Uinta
2502830      Washakie
2502831        Weston
Name: County, Length: 2502832, dtype: object

In [233]:
first_10_rows = covid_data.iloc[0:5]   ## Filtering the rows

In [239]:
first_10_rows

Date     County       State  Cases  Deaths
0  2020-01-21  Snohomish  Washington      1     0.0
1  2020-01-22  Snohomish  Washington      1     0.0
2  2020-01-23  Snohomish  Washington      1     0.0
3  2020-01-24       Cook    Illinois      1     0.0
4  2020-01-24  Snohomish  Washington      1     0.0

In [243]:
covid_data.loc[16:200]

Date       County          State  Cases  Deaths
16   2020-01-27         Cook       Illinois      1     0.0
17   2020-01-27    Snohomish     Washington      1     0.0
18   2020-01-28     Maricopa        Arizona      1     0.0
19   2020-01-28  Los Angeles     California      1     0.0
20   2020-01-28       Orange     California      1     0.0
..          ...          ...            ...    ...     ...
196  2020-02-17         Cook       Illinois      2     0.0
197  2020-02-17      Suffolk  Massachusetts      1     0.0
198  2020-02-17      Douglas       Nebraska     10     0.0
199  2020-02-17        Bexar          Texas      2     0.0
200  2020-02-17    Snohomish     Washington      1     0.0

[185 rows x 5 columns]

#### Conditional Filtering

In [264]:
Texas_covid_data = covid_data[covid_data['State'] == 'Texas']

In [268]:
Vital_Days = covid_data[covid_data['Deaths'] > 100]

In [276]:
Vital_Days.head(2)

Date         County     State  Cases  Deaths
7817  2020-03-22  New York City  New York   9065   119.0
9015  2020-03-23  New York City  New York  12329   155.0

In [272]:
Above_Avg_Death_Days = covid_data[covid_data['Deaths'] > covid_data['Deaths'].mean()]

In [278]:
Above_Avg_Death_Days.head(3)

Date         County     State  Cases  Deaths
10322  2020-03-24  New York City  New York  14943   230.0
11758  2020-03-25  New York City  New York  20061   330.0
13361  2020-03-26  New York City  New York  23182   435.0

In [294]:
covid_data.sort_values(by = 'Cases',ascending = False).head(10)  ## Order the Data by a column

Date       County       State    Cases   Deaths
2499779  2022-05-13  Los Angeles  California  2908425  32022.0
2496521  2022-05-12  Los Angeles  California  2904483  32016.0
2493263  2022-05-11  Los Angeles  California  2901153  32007.0
2490005  2022-05-10  Los Angeles  California  2898217  32000.0
2486748  2022-05-09  Los Angeles  California  2896104  31996.0
2480232  2022-05-07  Los Angeles  California  2889112  31991.0
2483490  2022-05-08  Los Angeles  California  2889112  31991.0
2476974  2022-05-06  Los Angeles  California  2889112  31991.0
2473716  2022-05-05  Los Angeles  California  2885879  31986.0
2470459  2022-05-04  Los Angeles  California  2882983  31982.0

In [298]:
covid_data[['State']].value_counts()

State                   
Texas                       193519
Georgia                     124889
Virginia                    103128
Kentucky                     92572
Missouri                     89600
Illinois                     79502
Kansas                       79294
North Carolina               77809
Iowa                         77070
Tennessee                    74719
Indiana                      71921
Nebraska                     69255
Ohio                         69101
Minnesota                    67883
Michigan                     65202
Mississippi                  64147
Oklahoma                     59923
Arkansas                     59032
Puerto Rico                  58397
Wisconsin                    55993
Florida                      53362
Pennsylvania                 52441
Alabama                      52312
Louisiana                    50902
South Dakota                 49552
Colorado                     49527
California                   45693
New York                     4

In [314]:
covid_summary = round(covid_data.describe(include='all').T,0)

In [316]:
covid_summary

count unique         top    freq          mean           std  min  \
Date      2502832    844  2022-05-13    3258           NaN           NaN  NaN   
County    2502832   1932  Washington   24215           NaN           NaN  NaN   
State     2502832     56       Texas  193519           NaN           NaN  NaN   
Cases   2502832.0    NaN         NaN     NaN  10033.804997  47525.217224  0.0   
Deaths  2445227.0    NaN         NaN     NaN    161.610023    820.333469  0.0   

          25%     50%     75%        max  
Date      NaN     NaN     NaN        NaN  
County    NaN     NaN     NaN        NaN  
State     NaN     NaN     NaN        NaN  
Cases   382.0  1773.0  5884.0  2908425.0  
Deaths    6.0    33.0   101.0    40267.0

In [320]:
# Shape
# Filtering using Multiple Conditions
# Adding a column
# to_datetime
# Merging/Appending Two or more Dataframes
# Grouping the Data (Equivalent to Pivoting in Excel)
# Pivoting in Python
# Treating Null Values and Outliers
# Duplicates
# EDA
# Clustering
# Ml Model Overview