In [3]:
import numpy as np   
import pandas as pd    
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import matplotlib.pyplot as plt   
import matplotlib.style

In [7]:
df = pd.read_csv('AirBNB.csv')

C:\Users\Admin\AppData\Local\Temp\ipykernel_19000\436833659.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('AirBNB.csv')


In [9]:
df.head()

id        room_type  accommodates  bathrooms cancellation_policy  \
0   6901257  Entire home/apt           3.0        1.0              strict   
1   6304928  Entire home/apt           7.0        1.0              strict   
2   7919400  Entire home/apt           5.0        1.0            moderate   
3  13418779  Entire home/apt           4.0        1.0            flexible   
4   3808709  Entire home/apt           2.0        1.0            moderate   

  cleaning_fee instant_bookable  review_scores_rating  bedrooms  beds  \
0         True                f                 100.0       1.0   1.0   
1         True                t                  93.0       3.0   3.0   
2         True                t                  92.0       1.0   3.0   
3         True                f                   NaN       2.0   2.0   
4         True                t                  40.0       0.0   1.0   

   log_price  
0   5.010635  
1   5.129899  
2   4.976734  
3   6.620073  
4   4.744932

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    74111 non-null  int64  
 1   room_type             74106 non-null  object 
 2   accommodates          74108 non-null  float64
 3   bathrooms             73908 non-null  float64
 4   cancellation_policy   74103 non-null  object 
 5   cleaning_fee          74107 non-null  object 
 6   instant_bookable      74111 non-null  object 
 7   review_scores_rating  57389 non-null  float64
 8   bedrooms              74019 non-null  float64
 9   beds                  73980 non-null  float64
 10  log_price             74111 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 6.2+ MB


In [15]:
round(df.describe().T,2)

count         mean         std    min         25%  \
id                    74111.0  11266617.10  6081734.89  344.0  6261964.50   
accommodates          74108.0         3.16        2.15    1.0        2.00   
bathrooms             73908.0         1.24        0.58    0.0        1.00   
review_scores_rating  57389.0        94.07        7.84   20.0       92.00   
bedrooms              74019.0         1.27        0.85    0.0        1.00   
beds                  73980.0         1.71        1.25    0.0        1.00   
log_price             74111.0         4.78        0.72    0.0        4.32   

                              50%          75%         max  
id                    12254147.00  16402260.50  21230903.0  
accommodates                 2.00         4.00        16.0  
bathrooms                    1.00         1.00         8.0  
review_scores_rating        96.00       100.00       100.0  
bedrooms                     1.00         1.00        10.0  
beds                         1.00         2.00        18.0  
log_price                    4.71         5.22         7.6

In [17]:
df.duplicated().sum()

0

In [44]:
df.drop('id',axis=1,inplace = True)

### Null Value Treatment

In [47]:
df.isnull().sum().sum()

17168

In [49]:
df.isnull().sum()

room_type                   5
accommodates                3
bathrooms                 203
cancellation_policy         8
cleaning_fee                4
instant_bookable            0
review_scores_rating    16722
bedrooms                   92
beds                      131
log_price                   0
dtype: int64

In [51]:
cat = []
num = []

In [53]:
for column in df.columns:
    if df[column].dtype != 'object':
        num.append(column)
    else:
        cat.append(column)

In [55]:
cat

['room_type', 'cancellation_policy', 'cleaning_fee', 'instant_bookable']

In [57]:
num

['accommodates',
 'bathrooms',
 'review_scores_rating',
 'bedrooms',
 'beds',
 'log_price']

In [59]:
for column in cat:
    mode = df[column].mode()[0]
    df[column].fillna(mode,inplace=True)

In [61]:
df.isnull().sum()

room_type                   0
accommodates                3
bathrooms                 203
cancellation_policy         0
cleaning_fee                0
instant_bookable            0
review_scores_rating    16722
bedrooms                   92
beds                      131
log_price                   0
dtype: int64

In [63]:
for column in num:
    median = df[column].median()
    df[column].fillna(median,inplace=True)

In [65]:
df.isnull().sum()

room_type               0
accommodates            0
bathrooms               0
cancellation_policy     0
cleaning_fee            0
instant_bookable        0
review_scores_rating    0
bedrooms                0
beds                    0
log_price               0
dtype: int64

In [80]:
df.head()

room_type  accommodates  bathrooms cancellation_policy  cleaning_fee  \
0  Entire home/apt           3.0        1.0              strict          True   
1  Entire home/apt           7.0        1.0              strict          True   
2  Entire home/apt           5.0        1.0            moderate          True   
3  Entire home/apt           4.0        1.0            flexible          True   
4  Entire home/apt           2.0        1.0            moderate          True   

  instant_bookable  review_scores_rating  bedrooms  beds  log_price  
0                f                 100.0       1.0   1.0   5.010635  
1                t                  93.0       3.0   3.0   5.129899  
2                t                  92.0       1.0   3.0   4.976734  
3                f                  96.0       2.0   2.0   6.620073  
4                t                  40.0       0.0   1.0   4.744932

In [86]:
for column in df.columns:
    if df[column].dtype == 'object':
        print(column.upper(),': ',df[column].nunique())
        print(df[column].value_counts().sort_values())
        print('\n')

ROOM_TYPE :  3
room_type
Shared room         2163
Private room       30635
Entire home/apt    41313
Name: count, dtype: int64


CANCELLATION_POLICY :  3
cancellation_policy
moderate    19060
flexible    22543
strict      32508
Name: count, dtype: int64


INSTANT_BOOKABLE :  2
instant_bookable
t    19451
f    54660
Name: count, dtype: int64




In [88]:
df['instant_bookable'].replace(['f','t'],[0,1],inplace = True)

In [90]:
df['cancellation_policy'].replace(['moderate','flexible','strict'],[0,1,2],inplace = True)

In [92]:
df.head()

room_type  accommodates  bathrooms  cancellation_policy  \
0  Entire home/apt           3.0        1.0                    2   
1  Entire home/apt           7.0        1.0                    2   
2  Entire home/apt           5.0        1.0                    0   
3  Entire home/apt           4.0        1.0                    1   
4  Entire home/apt           2.0        1.0                    0   

   cleaning_fee  instant_bookable  review_scores_rating  bedrooms  beds  \
0          True                 0                 100.0       1.0   1.0   
1          True                 1                  93.0       3.0   3.0   
2          True                 1                  92.0       1.0   3.0   
3          True                 0                  96.0       2.0   2.0   
4          True                 1                  40.0       0.0   1.0   

   log_price  
0   5.010635  
1   5.129899  
2   4.976734  
3   6.620073  
4   4.744932

In [102]:
df['cleaning_fee'].replace(['false','true'],[0,1],inplace = True)

In [96]:
df['room_type'].replace(['Shared room','Private room','Entire home/apt'],[0,1,2],inplace = True)

In [104]:
df.head()

room_type  accommodates  bathrooms  cancellation_policy  cleaning_fee  \
0          2           3.0        1.0                    2          True   
1          2           7.0        1.0                    2          True   
2          2           5.0        1.0                    0          True   
3          2           4.0        1.0                    1          True   
4          2           2.0        1.0                    0          True   

   instant_bookable  review_scores_rating  bedrooms  beds  log_price  
0                 0                 100.0       1.0   1.0   5.010635  
1                 1                  93.0       3.0   3.0   5.129899  
2                 1                  92.0       1.0   3.0   4.976734  
3                 0                  96.0       2.0   2.0   6.620073  
4                 1                  40.0       0.0   1.0   4.744932

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   room_type             74111 non-null  int64  
 1   accommodates          74111 non-null  float64
 2   bathrooms             74111 non-null  float64
 3   cancellation_policy   74111 non-null  int64  
 4   cleaning_fee          74111 non-null  bool   
 5   instant_bookable      74111 non-null  int64  
 6   review_scores_rating  74111 non-null  float64
 7   bedrooms              74111 non-null  float64
 8   beds                  74111 non-null  float64
 9   log_price             74111 non-null  float64
dtypes: bool(1), float64(6), int64(3)
memory usage: 5.2 MB


In [106]:
df.drop('cleaning_fee',axis = 1,inplace = True)

In [108]:
df.head()

room_type  accommodates  bathrooms  cancellation_policy  instant_bookable  \
0          2           3.0        1.0                    2                 0   
1          2           7.0        1.0                    2                 1   
2          2           5.0        1.0                    0                 1   
3          2           4.0        1.0                    1                 0   
4          2           2.0        1.0                    0                 1   

   review_scores_rating  bedrooms  beds  log_price  
0                 100.0       1.0   1.0   5.010635  
1                  93.0       3.0   3.0   5.129899  
2                  92.0       1.0   3.0   4.976734  
3                  96.0       2.0   2.0   6.620073  
4                  40.0       0.0   1.0   4.744932

## Model Building

In [111]:
X = df.drop('log_price',axis = 1)
y = df[['log_price']]

In [113]:
X.head()

room_type  accommodates  bathrooms  cancellation_policy  instant_bookable  \
0          2           3.0        1.0                    2                 0   
1          2           7.0        1.0                    2                 1   
2          2           5.0        1.0                    0                 1   
3          2           4.0        1.0                    1                 0   
4          2           2.0        1.0                    0                 1   

   review_scores_rating  bedrooms  beds  
0                 100.0       1.0   1.0  
1                  93.0       3.0   3.0  
2                  92.0       1.0   3.0  
3                  96.0       2.0   2.0  
4                  40.0       0.0   1.0

In [115]:
y.head()

log_price
0   5.010635
1   5.129899
2   4.976734
3   6.620073
4   4.744932

In [117]:
from sklearn.model_selection import train_test_split

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25 , random_state=1)

In [121]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(74111, 8)
(55583, 8)
(18528, 8)


In [123]:
print(y.shape)
print(y_train.shape)
print(y_test.shape)

(74111, 1)
(55583, 1)
(18528, 1)


In [125]:
Regression_model = LinearRegression()

In [127]:
Regression_model.fit(X_train,y_train)

LinearRegression()

In [129]:
Regression_model.coef_

array([[ 0.60113163,  0.07787843,  0.14853332,  0.02017706, -0.05529264,
         0.00706191,  0.14861097, -0.04656628]])

In [131]:
X.head()

room_type  accommodates  bathrooms  cancellation_policy  instant_bookable  \
0          2           3.0        1.0                    2                 0   
1          2           7.0        1.0                    2                 1   
2          2           5.0        1.0                    0                 1   
3          2           4.0        1.0                    1                 0   
4          2           2.0        1.0                    0                 1   

   review_scores_rating  bedrooms  beds  
0                 100.0       1.0   1.0  
1                  93.0       3.0   3.0  
2                  92.0       1.0   3.0  
3                  96.0       2.0   2.0  
4                  40.0       0.0   1.0

In [133]:
for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, Regression_model.coef_[0][idx]))

The coefficient for room_type is 0.6011316299263477
The coefficient for accommodates is 0.07787842769627926
The coefficient for bathrooms is 0.14853332173024783
The coefficient for cancellation_policy is 0.020177056618872275
The coefficient for instant_bookable is -0.055292637531991956
The coefficient for review_scores_rating is 0.007061909422977325
The coefficient for bedrooms is 0.148610969899994
The coefficient for beds is -0.04656628112380609


In [135]:
Regression_model.intercept_

array([2.64757265])

### Model Evaluation

In [140]:
Regression_model.score(X_train,y_train)

0.5158412344967042

In [142]:
Regression_model.score(X_test,y_test)

0.5119648431500052

In [144]:
Predicted_values = Regression_model.predict(X_test)

In [146]:
Predicted_values

array([[5.44036284],
       [4.3975868 ],
       [4.92084   ],
       ...,
       [5.05234662],
       [4.67456494],
       [4.27528108]])

In [148]:
np.sqrt(metrics.mean_squared_error(y_test,Predicted_values))

0.5026796798060691

## Classification Models

In [155]:
df['log_price'].max()

7.600402335

In [160]:
df['Price_Range'] = ['High' if x > 6 else 'Not High' for x in df['log_price']]

In [162]:
df.head()

room_type  accommodates  bathrooms  cancellation_policy  instant_bookable  \
0          2           3.0        1.0                    2                 0   
1          2           7.0        1.0                    2                 1   
2          2           5.0        1.0                    0                 1   
3          2           4.0        1.0                    1                 0   
4          2           2.0        1.0                    0                 1   

   review_scores_rating  bedrooms  beds  log_price Price_Range  
0                 100.0       1.0   1.0   5.010635    Not High  
1                  93.0       3.0   3.0   5.129899    Not High  
2                  92.0       1.0   3.0   4.976734    Not High  
3                  96.0       2.0   2.0   6.620073        High  
4                  40.0       0.0   1.0   4.744932    Not High

In [194]:
data = df.copy()

In [196]:
data.drop('log_price',axis=1,inplace = True)

In [198]:
data.head()

room_type  accommodates  bathrooms  cancellation_policy  instant_bookable  \
0          2           3.0        1.0                    2                 0   
1          2           7.0        1.0                    2                 1   
2          2           5.0        1.0                    0                 1   
3          2           4.0        1.0                    1                 0   
4          2           2.0        1.0                    0                 1   

   review_scores_rating  bedrooms  beds Price_Range  
0                 100.0       1.0   1.0    Not High  
1                  93.0       3.0   3.0    Not High  
2                  92.0       1.0   3.0    Not High  
3                  96.0       2.0   2.0        High  
4                  40.0       0.0   1.0    Not High

In [200]:
data['Price_Range'].replace(['High','Not High'],[1,0],inplace=True)

In [202]:
data

room_type  accommodates  bathrooms  cancellation_policy  \
0              2           3.0        1.0                    2   
1              2           7.0        1.0                    2   
2              2           5.0        1.0                    0   
3              2           4.0        1.0                    1   
4              2           2.0        1.0                    0   
...          ...           ...        ...                  ...   
74106          1           1.0        1.0                    1   
74107          2           4.0        2.0                    0   
74108          2           5.0        1.0                    0   
74109          2           2.0        1.0                    2   
74110          2           4.0        1.0                    0   

       instant_bookable  review_scores_rating  bedrooms  beds  Price_Range  
0                     0                 100.0       1.0   1.0            0  
1                     1                  93.0       3.0   3.0            0  
2                     1                  92.0       1.0   3.0            0  
3                     0                  96.0       2.0   2.0            1  
4                     1                  40.0       0.0   1.0            0  
...                 ...                   ...       ...   ...          ...  
74106                 0                  96.0       1.0   1.0            0  
74107                 0                  93.0       2.0   4.0            0  
74108                 1                  94.0       2.0   2.0            0  
74109                 1                  96.0       0.0   2.0            0  
74110                 0                  96.0       1.0   2.0            0  

[74111 rows x 9 columns]

In [204]:
data['Price_Range'].value_counts()

Price_Range
0    70252
1     3859
Name: count, dtype: int64

In [206]:
from sklearn.preprocessing import StandardScaler

In [222]:
Scaling = StandardScaler()

In [232]:
X = data.drop('Price_Range',axis = 1)
y = data[['Price_Range']]

In [234]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25 , random_state=1)

In [236]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(74111, 8)
(55583, 8)
(18528, 8)


In [238]:
X_train_Sca = Scaling.fit_transform(X_train)

In [240]:
X_test_Sca = Scaling.fit_transform(X_test)

In [244]:
X_train_Sca

array([[ 0.84817898,  3.18233733, -0.4040409 , ..., -0.07430135,
         3.19862654,  2.62902545],
       [ 0.84817898,  2.25178597, -0.4040409 , ..., -0.79550345,
         3.19862654,  1.82933015],
       [ 0.84817898, -0.07459244, -0.4040409 , ..., -0.50702261,
        -0.31504147,  0.22993955],
       ...,
       [ 0.84817898,  1.3212346 ,  1.32474592, ..., -0.21854177,
         2.02740387,  1.02963485],
       [ 0.84817898,  1.3212346 ,  2.18913932, ...,  0.21417949,
         0.8561812 ,  1.02963485],
       [ 0.84817898,  1.3212346 , -0.4040409 , ..., -0.79550345,
        -0.31504147, -0.56975574]])

In [246]:
X_test_Sca

array([[ 0.85790674,  0.85889913,  1.2923472 , ...,  0.79322039,
         0.88164168,  1.02927093],
       [-0.93959366, -0.06432899, -0.4022465 , ...,  0.07623398,
        -0.30162938,  0.23688585],
       [ 0.85790674, -0.52594305, -0.4022465 , ...,  0.07623398,
        -0.30162938,  0.23688585],
       ...,
       [ 0.85790674, -0.06432899, -0.4022465 , ...,  0.21963126,
        -0.30162938, -0.55549924],
       [ 0.85790674, -0.52594305, -0.4022465 , ..., -0.78414971,
        -1.48490045,  0.23688585],
       [-0.93959366, -0.9875571 , -0.4022465 , ...,  0.21963126,
        -0.30162938, -0.55549924]])

#### Logistic Regression

In [249]:
from sklearn.linear_model import LogisticRegression

In [251]:
LR = LogisticRegression()

In [253]:
LR.fit(X_train_Sca,y_train)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [261]:
y_train_predict = LR.predict(X_train_Sca)
model_score = LR.score(X_train_Sca, y_train)
print(model_score)
print()
print(metrics.confusion_matrix(y_train, y_train_predict))
print()
print(metrics.classification_report(y_train, y_train_predict))

0.9536548944821258

[[52369   344]
 [ 2232   638]]

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     52713
           1       0.65      0.22      0.33      2870

    accuracy                           0.95     55583
   macro avg       0.80      0.61      0.65     55583
weighted avg       0.94      0.95      0.94     55583



In [263]:
y_test_predict = LR.predict(X_test_Sca)
model_score = LR.score(X_test_Sca, y_test)
print(model_score)
print()
print(metrics.confusion_matrix(y_test, y_test_predict))
print()
print(metrics.classification_report(y_test, y_test_predict))

0.9518026770293609

[[17438   101]
 [  792   197]]

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     17539
           1       0.66      0.20      0.31       989

    accuracy                           0.95     18528
   macro avg       0.81      0.60      0.64     18528
weighted avg       0.94      0.95      0.94     18528



##### Decision Tree

In [268]:
from sklearn.tree import DecisionTreeClassifier

In [270]:
DT = DecisionTreeClassifier()

In [272]:
DT.fit(X_train_Sca,y_train)

DecisionTreeClassifier()

In [276]:
print('The Train Data Results')
y_train_predict = DT.predict(X_train_Sca)
model_score = DT.score(X_train_Sca, y_train)
print(model_score)
print()
print(metrics.confusion_matrix(y_train, y_train_predict))
print()
print(metrics.classification_report(y_train, y_train_predict))
print()
print('The Test Data Results')
print()
y_test_predict = DT.predict(X_test_Sca)
model_score = DT.score(X_test_Sca, y_test)
print(model_score)
print()
print(metrics.confusion_matrix(y_test, y_test_predict))
print()
print(metrics.classification_report(y_test, y_test_predict))

The Train Data Results
0.9732652069877481

[[52597   116]
 [ 1370  1500]]

              precision    recall  f1-score   support

           0       0.97      1.00      0.99     52713
           1       0.93      0.52      0.67      2870

    accuracy                           0.97     55583
   macro avg       0.95      0.76      0.83     55583
weighted avg       0.97      0.97      0.97     55583


The Test Data Results

0.9449481865284974

[[17246   293]
 [  727   262]]

              precision    recall  f1-score   support

           0       0.96      0.98      0.97     17539
           1       0.47      0.26      0.34       989

    accuracy                           0.94     18528
   macro avg       0.72      0.62      0.66     18528
weighted avg       0.93      0.94      0.94     18528



In [278]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier, AdaBoostClassifier

In [282]:
RF = RandomForestClassifier()
RF.fit(X_train_Sca,y_train)
print()
print()
print('The Train Data Results')
print()
y_train_predict = RF.predict(X_train_Sca)
model_score = RF.score(X_train_Sca, y_train)
print(model_score)
print()
print(metrics.confusion_matrix(y_train, y_train_predict))
print()
print(metrics.classification_report(y_train, y_train_predict))
print()
print('The Test Data Results')
print()
y_test_predict = RF.predict(X_test_Sca)
model_score = RF.score(X_test_Sca, y_test)
print(model_score)
print()
print(metrics.confusion_matrix(y_test, y_test_predict))
print()
print(metrics.classification_report(y_test, y_test_predict))

C:\Users\Admin\AppData\Local\Temp\ipykernel_19000\1375018359.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RF.fit(X_train_Sca,y_train)




The Train Data Results

0.9732472158753576

[[52540   173]
 [ 1314  1556]]

              precision    recall  f1-score   support

           0       0.98      1.00      0.99     52713
           1       0.90      0.54      0.68      2870

    accuracy                           0.97     55583
   macro avg       0.94      0.77      0.83     55583
weighted avg       0.97      0.97      0.97     55583


The Test Data Results

0.9502374784110535

[[17330   209]
 [  713   276]]

              precision    recall  f1-score   support

           0       0.96      0.99      0.97     17539
           1       0.57      0.28      0.37       989

    accuracy                           0.95     18528
   macro avg       0.76      0.63      0.67     18528
weighted avg       0.94      0.95      0.94     18528



##### Gradient Boost

In [285]:
GB = GradientBoostingClassifier()
GB.fit(X_train_Sca,y_train)
print()
print()
print('The Train Data Results')
print()
y_train_predict = GB.predict(X_train_Sca)
model_score = GB.score(X_train_Sca, y_train)
print(model_score)
print()
print(metrics.confusion_matrix(y_train, y_train_predict))
print()
print(metrics.classification_report(y_train, y_train_predict))
print()
print('The Test Data Results')
print()
y_test_predict = GB.predict(X_test_Sca)
model_score = GB.score(X_test_Sca, y_test)
print(model_score)
print()
print(metrics.confusion_matrix(y_test, y_test_predict))
print()
print(metrics.classification_report(y_test, y_test_predict))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)




The Train Data Results

0.9553100768220499

[[52337   376]
 [ 2108   762]]

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     52713
           1       0.67      0.27      0.38      2870

    accuracy                           0.96     55583
   macro avg       0.82      0.63      0.68     55583
weighted avg       0.95      0.96      0.95     55583


The Test Data Results

0.9538536269430051

[[17440    99]
 [  756   233]]

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     17539
           1       0.70      0.24      0.35       989

    accuracy                           0.95     18528
   macro avg       0.83      0.61      0.66     18528
weighted avg       0.94      0.95      0.94     18528

